### PR TITLE
Elevator indicators. Closes #14

### LINKED ISSUE #14: Elevator up/down indications aren't visible on display
The elevator up/down indications that are set by `goingUpIndicator()` and `goingDownIndicator()` aren't visible on the elevator display. An arrow on the elevator itself would help when writing scripts that use this functionality.

### PR DESCRIPTION
**Pull request by bumbu**

### CODE REVIEW

**Comment by magwo** [comment]
Nice! This pull request contains a lot of things though, some of which are already fixed (like logging removal and page width tweak). I would prefer if it contained only the things regarding up/down indicators.

**Comment by bumbu** [comment]
Sorry, my bad. Accidentally committed  these things (those git aliases, you know...)

**Comment by bumbu** [comment]
Should be good now.

**Comment by roryokane** [comment]
Link to the issue in the title: #14 “Elevator up/down indications aren't visible on display”

**Comment by bumbu** [comment]
Should I add `#14` as title to a commit, or I should remove that from pull request title?

**Comment by magwo** [comment]
No I think it's fine.

**Comment by magwo** [comment]
Never mind, I think I've got some ideas.. will merge and do some changes.

**Pull request merged**
