### PR TITLE
Interface for getting pressed floors of an elevator (fixes #35).

### LINKED ISSUE #35: Add direct way to get an array of pressed floor numbers
When people press the floor buttons in the elevator the little numbers light up visually to indicate which floors have been pressed but there is no way to directly get an array of those numbers in the code. Instead one would have to manually keep track of all those which is rather inconvenient, especially when the system actually already exists.

### PR DESCRIPTION
**Pull request by sim642**
Remove undocumented function getFirstPressedFloor.

### CODE REVIEW

**Comment by magwo** [comment]
Nice. I would prefer to name the function:
    getFloorButtonStates()

**Comment by magwo** [comment]
Hmmm.. or maybe that should be a separate function. This one is like a helper function I suppose.

**Comment by sim642** [comment]
The internal elevator.buttonStates is an array of booleans for each floor but this function returns the numbers of the floors which have true in that. I thought this would be more useful as more often you'd want to know if any floors are pressed or get the first/last pressed floor or maybe even get the next pressed floor up/down from your current floor. Having a function return the boolean states would mean having to do that iteration manually every time any kind of such operation is wanted. But this is just my opinion...

**Comment by magwo** [comment]
Yeah this is good.

**Comment by magwo** [comment]
I will merge and then put back the removed function with a deprecation warning. Don't want to break people's code more than necessary.

**Pull request merged**
