### PR TITLE
Automatic testing with Selenium and Ranking generation

### PR DESCRIPTION
**Pull request by rachkoud**
Hi, you did an awesome job by creating this challenging game!

I added Gulp to test automatically all solutions or a solution with Selenium and generate a ranking based on the total percent of all challenges.

I completed the README.md : 

### Testing

To test your solution automatically with Selenium you must install the node packages :
```Shell
npm install
```

Then, you must install [ChromeDriver](https://code.google.com/p/selenium/wiki/ChromeDriver), with OS X, you can use brew : 

```Shell
brew install chromedriver
```

To generate the stats and test your solution automatically, you can run this command : 

```Shell
gulp --challenges 1,2 --numberOfTestsPerChallenge 10 --solutionToTest alber70g.solution.js --timeScale 21
```
**Parameters**

* **--challenges** (default : 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17) : challenges to run, separated with a comma.
* **--numberOfTestsPerChallenge** (default : 1) : number of test to execute for each challenge.
* **--solutionToTest** (default : null, all solutions are tested) : solution to test (must be in the folder solutions/working with the extension .solution.js).
* **--timeScale** (default : 21) : time scale (speed), must be in that range 1, 2, 3, 5, 8, 13, 21.

After the solution test, a stats file is written in : 

```Shell
Write stats : solutions/working/username.solution.stats.json
```

Note : If you run gulp without any parameters, it will test all solutions, which take approximativaly 6 hours for 29 solutions.

### Ranking
A ranking file, based on the total percent of each challenge, can be generated in solutions/working/ranking.md by using all solutions/working/*.solution.stats.json : 

```Shell
gulp ranking
```

So if you want to calculate your ranking, you can test your solution automatically and then generate the ranking.

Note : Each challenge of each solution must be tested the same number of times.

The ranking of [all solutions](https://github.com/magwo/elevatorsaga/wiki/Solutions) has been generated : [See ranking](https://github.com/rachkoud/elevatorsaga/blob/master/solutions/working/ranking.md)

### CODE REVIEW

**Comment by efouts** [comment]
Should this be pointing to the live site or a config value for a local one? https://github.com/rachkoud/elevatorsaga/blob/master/stats.js#L238

**Comment by larva** [comment]
Might I suggest leaving out the huge set of solutions gathered from the Wiki? I think they actually detract from the value of your work.

Perhaps splitting up the commit into one initial commit that adds the critical gulp bits and other commits with the solutions would be better.

Few of the solutions posted to the wiki ought to be incorporated the repository. They are in the wiki to inform players -- not as test cases. A few that are chosen for incorporation into the repository should provide testing coverage and a small set of solutions that are known to work because they are testcases.

The rest should not be incorporated because the solutions will presumably change too -- arguably more often than the game itself -- and adding them to the game repository could mean lots of commits just to keep all of the solutions up-to-date. If the solutions are meant to test for functional or API changes that could be fine however they don't seem to be carefully crafted for that purpose. So I think selecting a small number of them for incorporation would be best.

Maybe use the initial default solution and the output of that. That nicely balances keeping the first commit small, keeping the repository small, easily shows others how to run gulp, and what kinds results they can expect to see. Then pick as few solutions that cover the game code as possible and add about one per commit. That would also allow you to nicely attribute the solutions to their authors in the git log.

**Comment by rachkoud** [comment]
@efouts It's pointing to my local solution, but I will add a parameter gameUrl with the default value http://play.elevatorsaga.com/ 

@larva You're right maybe I can start with a small commit, but the main idea is to create an automatic testing solution where you can select the challenges you want to test and get a stats file. And the other idea is to create a ranking, because on the wiki, there are few solutions with some stats, but there isn't any ranking with a global testing solution. Maybe we can create another repo with the solutions and then we can use the github api directly in the gulp ranking task to retrieve the solutions and build a ranking? Another idea?

**Comment by magwo** [comment]
This is pretty nice and impressive. However, the whole game is written with testability in mind, so it WOULD, with some modifications, be possible to do this completely with "unit" testing - meaning pure javascript execution and no Selenium or web driver involvement.

See for example https://github.com/magwo/elevatorsaga/blob/master/world.js#L202 where an animation frame requester is injected, meaning this can easily be mocked to drive the whole game loop in javascript. This would be _much_ faster to execute. The 6 hours you mention could probably be reduced to 10 minutes or something.

What do you think?

**Comment by rachkoud** [comment]
@magwo To be honest the first thing I did was to search if a unit test already exists and it was weird why there was no test even a small one. Then I started thinking to the best way to implement that and I decided to use a end to end test because it's the closest way to what we do when we apply our solution and many times a end to end test is a good solution because it tests the whole solution, but the downside is the poor performance. I think we can keep both solutions, because they are both valuable. In the meantime, I created a small unit test : 

```javascript
describe("Solution tester", function() {
    jasmine.DEFAULT_TIMEOUT_INTERVAL = 200000;
    var frameRequester = null;
    var DT_MAX = 1.0 / 60.0;
    var createFrameRequester = function(timeStep) {
        var currentT = 0.0;
        var currentCb = null;
        return {
            register: function(cb) { currentCb = cb; },
            trigger: function() { currentT += timeStep; if(currentCb !== null) { currentCb(currentT); } }
        };
    };
    beforeEach(function() {
        frameRequester = createFrameRequester(1000.0);
    });
    it("solution X works with challenge 1", function(done) {
        var challengeIndex = 0;
        var worldCreator = createWorldCreator();
        var world = worldCreator.createWorld(challenges[challengeIndex].options);
        var worldController = createWorldController(DT_MAX);
        worldController.timeScale = 1;

        var solutionX = {
            name: 'Name...',
            url: 'https://github.com/...',
            init: function(elevators, floors) {},
            update: function(dt, elevators, floors) {}
        };

        worldController.start(world, solutionX, frameRequester.register, true);

        setInterval(function() {
          frameRequester.trigger();
        }, 1);

        world.on("stats_changed", function() {
            var challengeStatus = challenges[0].condition.evaluate(world);
            if(challengeStatus !== null) {
                world.challengeEnded = true;
                worldController.setPaused(true);
                console.log('challengeStatus : ' + challengeStatus);
                console.log('transportedCounter : ' + world.transportedCounter);
                console.log('elapsedTime : ' + world.elapsedTime.toFixed(0));
                console.log('transportedPerSec : ' + world.transportedPerSec.toPrecision(3));
                console.log('avgWaitTime : ' + world.avgWaitTime.toFixed(1));
                console.log('maxWaitTime . ' + world.maxWaitTime.toFixed(1));
                console.log('moveCount : ' + world.moveCount);
                expect(challengeStatus).toBe(true);
                done();
            }
        });
    });
});
```

But the problem remains the same, where should we take the solutions from? Where should generate the ranking? With the browser, it's harder to access to the file system due to the security. What do you think?

**Comment by magwo** [comment]
I'm sorry but this PR is just waaayy too big and increases the project size vastly.. Even GitHub breaks down trying to show the commit.

I've just now introduced a fitness calculator concept, which runs the simulation in the background, preferrably in a Web Worker. This is very very fast and compact, and is the way forward towards more comparable performance tests.

https://github.com/magwo/elevatorsaga/commit/ea6f24128cceda1c3ad82cd3137c55c717dd9a95

**Pull request closed without merging**
